### ISSUE TITLE
"Embed workspace documents" doesn't work properly 

### ISSUE THREAD

**Issue by makiz1999** [twinnydotdev/twinny#384]
**Describe the bug**
I am trying to use embeddings to create context awareness of myry so that I can ask a current directo chatbot for details within a file. I have a python file with a simple function:
![image](https://github.com/user-attachments/assets/5f0c46ef-7599-4f80-9d80-5b4e4bc17c1e)

And this is chatbot response:
![image](https://github.com/user-attachments/assets/bb0742db-ac56-4d83-8ef6-f39f1210a114)

**Logging**
After embedding workspace documents:
![image](https://github.com/user-attachments/assets/9a611b57-6947-431d-83af-bf70096d6ee0)

**API Provider**
![image](https://github.com/user-attachments/assets/53ced8c0-6cc7-46e1-bf13-5da8f096239f)

**Chat or Auto Complete?**
Chat

**Model Name**
`codellama:7b-instruct`

**Desktop (please complete the following information):**
 - OS: macOS: Sequoia 15.1
 - Version v3.18.12

**Comment by rjmacarthy** [comment]
Hey, thanks for the report. Please could you explain why you are using `codellama:7b-instruct` as the embedding model?

**Comment by makiz1999** [comment]
> Hey, thanks for the report. Please could you explain why you are using `codellama:7b-instruct` as the embedding model?

Hi, I was experimenting with different models to see if the output or quality of responses would change. From my observations, responses are pretty much similar to any model. I get a similar error when using `llama3.1:latest`:
![image](https://github.com/user-attachments/assets/2e75840d-a4c8-4959-b11b-eb2023b5f0a0)

![image](https://github.com/user-attachments/assets/b8b8d71c-b3ce-4754-bf07-00e67b13ed9c)

![image](https://github.com/user-attachments/assets/d7174510-9b17-4b40-9ce2-609272cbce48)

The response with `llama3.1:latest` is different but still doesn't make sense and reference the actual file.

Do you know by chance how to fix it? Thanks

**Comment by rjmacarthy** [comment]
Interesting, would have to investigate, maybe something changed with LanceDB recently...

**Comment by rjmacarthy** [comment]
Hey, I just released version 3.19.0.  I would recommend to use https://ollama.com/library/all-minilm for the embedding model, this is the one I have had best results with in the past, let me know if you find a better one.

Many thanks!

**Comment by makiz1999** [comment]
> Hey, I just released version 3.19.0. I would recommend to use https://ollama.com/library/all-minilm for the embedding model, this is the one I have had best results with in the past, let me know if you find a better one.
> 
> Many thanks!

Thank you so much! I will try to test it out soon. Do you have recommendations for chat and FIM models as well?

**Comment by makiz1999** [comment]
I have installed `all-minilm` and set it up as the embedding model. It still doesn't work as expected unfortunately and can't reference other files. Here is the error after pressing 'Embed workspace documents'.
![image](https://github.com/user-attachments/assets/fd271abb-b57e-4c64-97e9-19efb550b784)

**Comment by rjmacarthy** [comment]
I think maybe your folder has a space in the name? Please try to remove the space for now. I'll fix that bug in the next release.

Many thanks.
